kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
    - docker build -t telegity .
  when:
    branch:
      - master

- name: run
  commands:
    - cd /var/docker/telegity
    #- docker-compose stop telegity
    - docker-compose up -d telegity
  when:
  branch:
    - master